spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/hbh
#    url: jdbc:mysql://localhost:3306/hbh
  #    url: jdbc:h2:mem:default
    username: root
    password:
#    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    use-generated-keys: true
    default-executor-type: simple
    default-statement-timeout: 10
    call-setters-on-nulls: true

  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.example.demo.entity

logging:
    level:
      org.springframework.transaction.interceptor: TRACE