spring:
jpa:
hibernate:
ddl-auto:create
properties:
hibernate:
globally_quoted_identifiers:true # ??????, ??? "" ? ??????, ????? ?????? ?? (table, order, view ?)
datasource:
url:jdbc:h2:mem:default
driver-class-name:org.h2.Driver
h2:
console:
enabled:true